[features]
seeds = false
skip-lint = false

[programs.localnet]
staking = "5XGNhkfaqMQYEVNwh2DvpAZbtX7yPkiWX2JQKxwopnD2"

[programs.devnet]
staking = "5XGNhkfaqMQYEVNwh2DvpAZbtX7yPkiWX2JQKxwopnD2"

[programs.mainnet]
staking = "5XGNhkfaqMQYEVNwh2DvpAZbtX7yPkiWX2JQKxwopnD2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tests/tsconfig.json -t 1000000 tests/**/*.ts"
